### ISSUE TITLE
Ukrainian transliteration standarts

### ISSUE THREAD

**Issue by jaskierLTD** [ElForastero/Transliterate#12]
My friend has used your libraries but as for me, there are no standards for Ukrainian transliteration. Wrong conversion.
I could help with this question... 
jaskierltd@gmail.com

**Comment by ElForastero** [comment]
Hi, @jaskierLTD.

Sure, would appreciate any help. Frankly saying I didn't add ukrainian maps just because I haven't used them.

But I left an ability to add custom maps. If you'll help, we can add it to the package.

**Comment by RolandVerner** [comment]
https://zakon.rada.gov.ua/laws/show/55-2010-%D0%BF#Text

**Comment by ElForastero** [comment]
Just to be more clear here, anyone can contribute additional transliteration maps.

If you use something in production and think that it's better for them to be in the core package, just submit a PR please 🙏

Since I'm not using this package for a long time, I would leave these contribution for community
